# .travis.yml

language: python
python: 3.7
cache: pip
dist: xenial
addons:
  postgresql: 10
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - psql -c 'CREATE DATABASE twitter_api_flask_development;' -U postgres
env:
  - DATABASE_URL="postgresql://postgres:postgres@localhost:5433/twitter_api_flask"
script:
  - pipenv run nosetests